project:
  type: website

website:
  title: "Solène Berney"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: DSF_quarto_publish.qmd
        text: Public Transport Passenger Forecast
      - href: Strava_quarto_publish.qmd
        text: Strava Map
        
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/solene-berney-unisg/
        aria-label: LinkedIn
      - icon: envelope
        href: "mailto:solenebny@gmail.com"
        aria-label: Email
  
  page-footer:
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/solène-berney-unisg/


format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

editor: visual

